server:
  port: 8581
  servlet:
    context-path: /api

spring:
  application:
    name: model-app
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
  datasource:
    url: jdbc:h2:file:../../data/cars;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

springdoc:
  packagesToScan: cl.andres.models.controller